// AUTO-GENERATED by packages/ai-context/src/generate.ts
// Do not edit manually. Run: pnpm --filter @we/ai-context generate-context

export const contextToolDefs = [
  {
    name: 'we_stores_reference',
    description:
      'Load the store members, computed state, actions, and access patterns section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'we_schema_operators',
    description:
      'Load the schema node types, operator catalogue, and function library section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'we_component_registry',
    description:
      'Load the primitive and component tags with props, slots, and descriptions section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'we_common_patterns',
    description: 'Load the ready-made layout and form template recipes section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'we_design_props',
    description:
      'Load the design system property tables inherited by all primitives section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'we_plugin_registries',
    description:
      'Load the plugin catalogues and named-plugin configuration options section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'we_store_patterns',
    description: 'Load the store creation and data-binding usage patterns section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'we_panels',
    description: 'Load the panel types, configuration, and section layout section of the WE schema reference.',
    parameters: { type: 'object', properties: {} },
  },
] as const;
